# setup-secrets.ps1 - one-time setup of the private values that must NOT live in git.
# Writes invite.secret and admin.password.hash into android-app\local.properties (git-ignored).
# Run it once on each PC that builds the release APK. Use the SAME values on every admin PC,
# otherwise invite codes generated by different admins will not match.
$ErrorActionPreference = 'Stop'
Set-Location -Path $PSScriptRoot
$lp = Join-Path $PSScriptRoot 'android-app\local.properties'
if (-not (Test-Path $lp)) { New-Item -ItemType File -Path $lp -Force | Out-Null }
$lines = @(Get-Content -Path $lp -Encoding utf8 | Where-Object { $_ -ne $null })

function Get-Prop($name) {
    foreach ($l in $lines) { if ($l -match "^\s*$([regex]::Escape($name))\s*=\s*(.*)$") { return $Matches[1].Trim() } }
    return ''
}
function Set-Prop($name, $value) {
    $script:lines = @($script:lines | Where-Object { $_ -notmatch "^\s*$([regex]::Escape($name))\s*=" })
    $script:lines += "$name=$value"
}

$secret = Get-Prop 'invite.secret'
if ($secret) {
    Write-Host "invite.secret already set (kept)."
} else {
    $ans = Read-Host "Paste the invite secret from your other PC, or press Enter to generate a new random one"
    if ($ans.Trim()) { $secret = $ans.Trim() } else {
        $bytes = New-Object byte[] 32
        [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
        $secret = [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+','x').Replace('/','y')
        Write-Host ""
        Write-Host "NEW invite secret (save it in a password manager; other admin PCs need the SAME value):"
        Write-Host $secret
    }
    Set-Prop 'invite.secret' $secret
}

$existingHash = Get-Prop 'admin.password.hash'
$change = $true
if ($existingHash) { $change = ((Read-Host "admin.password.hash already set. Replace it? (y/N)") -eq 'y') }
if ($change) {
    $sec = Read-Host "Choose the admin password (6+ chars)" -AsSecureString
    $pw = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
    if ($pw.Length -lt 6) { Write-Host "Too short (min 6). Nothing changed."; exit 1 }
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $hash = ($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes("${secret}:${pw}")) | ForEach-Object { $_.ToString('x2') }) -join ''
    Set-Prop 'admin.password.hash' $hash
}

[System.IO.File]::WriteAllLines($lp, [string[]]$lines, (New-Object System.Text.UTF8Encoding($false))) # no BOM: a BOM breaks sdk.dir
Write-Host ""
Write-Host "Saved to $lp . Now run build-apk.bat."
